// Generated by CoffeeScript 1.6.3
(function() {
  var layersApp;

  layersApp = angular.module("layersApp", ["hmTouchevents"]);

  layersApp.controller("IndexCtrl", function($scope) {
    $scope.openShow = function() {
      var showView;
      showView = new steroids.views.WebView("views/layers/show.html");
      return steroids.layers.push(showView);
    };
    return steroids.view.navigationBar.show("Index");
  });

  layersApp.controller("ShowCtrl", function($scope) {
    var deleted;
    $scope.openEdit = function() {
      var editView;
      editView = new steroids.views.WebView("views/layers/edit.html");
      return steroids.layers.push(editView);
    };
    deleted = false;
    document.addEventListener("visibilitychange", function() {
      console.log("Show view is " + document.visibilityState);
      if (document.visibilityState === "visible") {
        if (deleted) {
          deleted = false;
          return setTimeout(function() {
            return steroids.layers.pop();
          }, 1000);
        }
      }
    });
    window.addEventListener("message", function(msg) {
      if (msg.data.id === 34) {
        if (msg.data.action === "delete") {
          return deleted = true;
        }
      }
    });
    return steroids.view.navigationBar.show("Show");
  });

  layersApp.controller("EditCtrl", function($scope) {
    $scope["delete"] = function() {
      var message;
      message = {
        id: 34,
        action: "delete"
      };
      window.postMessage(message, "*");
      return steroids.layers.pop();
    };
    return steroids.view.navigationBar.show("Edit");
  });

}).call(this);
